<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>CascadeControls</RootNamespace>
    <IsAotCompatible>true</IsAotCompatible>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Description>A Cascade UI control library.</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Echostorm.Cascade.UI" Version="0.1.0-*" />
  </ItemGroup>

</Project>
