<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Cascade.IDE.Shared</RootNamespace>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Cascade.UI.Tests" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Cascade.UI\Cascade.UI.csproj" />
  </ItemGroup>
</Project>
