<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>Cascade.UI.CliFixture</AssemblyName>
    <RootNamespace>Cascade.UI.CliFixture</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Cascade.UI\Cascade.UI.csproj" />
  </ItemGroup>

</Project>
