<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>SimpleCascade</AssemblyName>
    <RootNamespace>SimpleCascade</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IsAotCompatible>true</IsAotCompatible>

    <PublishAot Condition="'$(Configuration)' == 'Release'">true</PublishAot>
    <InvariantGlobalization>true</InvariantGlobalization>
    <StripSymbols>true</StripSymbols>

    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <CompilerGeneratedFilesOutputPath>$(BaseIntermediateOutputPath)Generated</CompilerGeneratedFilesOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Cascade.UI\Cascade.UI.csproj" />
    <ProjectReference Include="..\..\src\Cascade.UI.Installer\Cascade.UI.Installer.csproj" />
  </ItemGroup>

  <Import Project="..\..\src\Cascade.UI\build\Cascade.UI.targets" />

</Project>
