using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Text;

namespace Cascade.Generators.Tests;

/// <summary>
/// Tests for the font verification source generator pipeline (WP-201).
/// Each test provides synthetic font AdditionalFiles with metadata and
/// verifies that the generator produces the expected Fonts class or diagnostics.
/// </summary>
public class FontVerifierTests
{
    // ── Basic font generation ─────────────────────────────────────────

    [TUnit.Core.Test]
    public async Task FontFile_GeneratesFontsClass()
    {
        var result = RunWithFontFiles(("fonts/Roboto-Regular.ttf", "fake-font-content", true));
        var generated = GetGeneratedSource(result, "Fonts.g.cs");

        await TUnit.Assertions.Assert.That(generated).IsNotNull();
        await TUnit.Assertions.Assert.That(Has(generated, "public static partial class Fonts")).IsTrue();
        await TUnit.Assertions.Assert.That(Has(generated, "RobotoRegular")).IsTrue();
    }

    // ── Multiple fonts ────────────────────────────────────────────────

    [TUnit.Core.Test]
    public async Task MultipleFonts_AllGenerated()
    {
        var result = RunWithFontFiles(
            ("fonts/Roboto-Regular.ttf", "fake-font-content", true),
            ("fonts/Inter-Bold.otf", "fake-font-content", true));
        var generated = GetGeneratedSource(result, "Fonts.g.cs");

        await TUnit.Assertions.Assert.That(generated).IsNotNull();
        await TUnit.Assertions.Assert.That(Has(generated, "RobotoRegular")).IsTrue();
        await TUnit.Assertions.Assert.That(Has(generated, "InterBold")).IsTrue();
    }

    // ── Auto-generated header ─────────────────────────────────────────

    [TUnit.Core.Test]
    public async Task GeneratedCode_HasAutoGeneratedHeader()
    {
        var result = RunWithFontFiles(("fonts/Test.ttf", "font-data", true));
        var generated = GetGeneratedSource(result, "Fonts.g.cs");

        await TUnit.Assertions.Assert.That(generated).IsNotNull();
        await TUnit.Assertions.Assert.That(Has(generated, "// <auto-generated/>")).IsTrue();
    }

    // ── No font files ─────────────────────────────────────────────────

    [TUnit.Core.Test]
    public async Task NoFontFiles_NoGeneratedSource()
    {
        var result = RunWithNoAdditionalFiles();
        var generated = GetGeneratedSource(result, "Fonts.g.cs");

        await TUnit.Assertions.Assert.That(generated is null).IsTrue();
    }

    // ── Font name conversion ──────────────────────────────────────────

    [TUnit.Core.Test]
    public async Task FontName_DashesConvertedToPascalCase()
    {
        var result = RunWithFontFiles(("fonts/open-sans-bold.ttf", "font-data", true));
        var generated = GetGeneratedSource(result, "Fonts.g.cs");

        await TUnit.Assertions.Assert.That(generated).IsNotNull();
        await TUnit.Assertions.Assert.That(Has(generated, "OpenSansBold")).IsTrue();
    }

    // ── Test infrastructure ───────────────────────────────────────────

    private static bool Has(string? source, string value)
    {
        return source is not null && source.Contains(value, StringComparison.Ordinal);
    }

    private static GeneratorRunResult RunWithFontFiles(
        params (string Path, string Content, bool IsCascadeFont)[] files)
    {
        var additionalTexts = files
            .Select(f => (AdditionalText)new InMemoryAdditionalText(f.Path, f.Content))
            .ToImmutableArray();

        var optionsByFile = new Dictionary<string, Dictionary<string, string>>();
        foreach (var file in files)
        {
            if (file.IsCascadeFont)
            {
                optionsByFile[file.Path] = new Dictionary<string, string>
                {
                    ["build_metadata.AdditionalFiles.CascadeFont"] = "true"
                };
            }
        }

        return RunGenerator(additionalTexts, optionsByFile);
    }

    private static GeneratorRunResult RunWithNoAdditionalFiles()
    {
        return RunGenerator(
            ImmutableArray<AdditionalText>.Empty,
            new Dictionary<string, Dictionary<string, string>>());
    }

    private static GeneratorRunResult RunGenerator(
        ImmutableArray<AdditionalText> additionalTexts,
        Dictionary<string, Dictionary<string, string>> optionsByFile)
    {
        var source = "// Empty compilation";
        var syntaxTree = CSharpSyntaxTree.ParseText(source);

        var references = new List<MetadataReference>();
        foreach (var assembly in AppDomain.CurrentDomain.GetAssemblies())
        {
            if (!assembly.IsDynamic && !string.IsNullOrEmpty(assembly.Location))
            {
                try
                {
                    references.Add(MetadataReference.CreateFromFile(assembly.Location));
                }
                catch
                {
                    // Some assemblies may not be loadable — skip
                }
            }
        }

        var compilation = CSharpCompilation.Create(
            "TestAssembly",
            new[] { syntaxTree },
            references,
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

        var optionsProvider = new TestAnalyzerConfigOptionsProvider(optionsByFile);

        var generator = new CascadeGenerator();
        GeneratorDriver driver = CSharpGeneratorDriver.Create(
            generators: new[] { generator.AsSourceGenerator() },
            additionalTexts: additionalTexts,
            optionsProvider: optionsProvider);

        driver = driver.RunGeneratorsAndUpdateCompilation(
            compilation, out _, out _);

        return driver.GetRunResult().Results[0];
    }

    private static string? GetGeneratedSource(GeneratorRunResult result, string hintName)
    {
        foreach (var source in result.GeneratedSources)
        {
            if (source.HintName == hintName)
            {
                return source.SourceText.ToString();
            }
        }
        return null;
    }
}

/// <summary>
/// Test implementation of <see cref="AnalyzerConfigOptionsProvider"/>
/// that provides per-file metadata for font verification tests.
/// </summary>
internal sealed class TestAnalyzerConfigOptionsProvider : AnalyzerConfigOptionsProvider
{
    private readonly Dictionary<string, Dictionary<string, string>> optionsByFile;

    public TestAnalyzerConfigOptionsProvider(Dictionary<string, Dictionary<string, string>> optionsByFile)
    {
        this.optionsByFile = optionsByFile;
    }

    public override AnalyzerConfigOptions GlobalOptions => TestAnalyzerConfigOptions.Empty;

    public override AnalyzerConfigOptions GetOptions(SyntaxTree tree)
    {
        return TestAnalyzerConfigOptions.Empty;
    }

    public override AnalyzerConfigOptions GetOptions(AdditionalText textFile)
    {
        if (optionsByFile.TryGetValue(textFile.Path, out var options))
        {
            return new TestAnalyzerConfigOptions(options);
        }
        return TestAnalyzerConfigOptions.Empty;
    }
}

internal sealed class TestAnalyzerConfigOptions : AnalyzerConfigOptions
{
    public static readonly TestAnalyzerConfigOptions Empty =
        new(new Dictionary<string, string>());

    private readonly Dictionary<string, string> options;

    public TestAnalyzerConfigOptions(Dictionary<string, string> options)
    {
        this.options = options;
    }

    public override bool TryGetValue(string key, [System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out string? value)
    {
        return options.TryGetValue(key, out value);
    }
}
