using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

namespace Cascade.Generators.Tests;

/// <summary>
/// Tests for the icon pack source generator pipeline (WP-201).
/// Each test provides synthetic SVG AdditionalFiles and verifies that
/// the generator produces the expected icon class with static fields.
/// </summary>
public class IconPackGeneratorTests
{
    private const string SimpleSvg = @"<svg viewBox=""0 0 24 24"" xmlns=""http://www.w3.org/2000/svg"">
  <path d=""M12 2L2 22h20L12 2z""/>
</svg>";

    private const string MultiPathSvg = @"<svg viewBox=""0 0 24 24"" xmlns=""http://www.w3.org/2000/svg"">
  <path d=""M12 2L2 22h20L12 2z""/>
  <path d=""M12 8v8""/>
</svg>";

    // ── Basic icon generation ─────────────────────────────────────────

    [TUnit.Core.Test]
    public async Task SingleSvg_GeneratesIconField()
    {
        var result = RunWithIconFiles(("icons/lucide/arrow-left.svg", SimpleSvg));
        var generated = GetGeneratedSource(result, "LucideIcons.g.cs");

        await TUnit.Assertions.Assert.That(generated).IsNotNull();
        await TUnit.Assertions.Assert.That(Has(generated, "public static readonly global::Cascade.UI.Icon ArrowLeft")).IsTrue();
        await TUnit.Assertions.Assert.That(Has(generated, "M12 2L2 22h20L12 2z")).IsTrue();
    }

    [TUnit.Core.Test]
    public async Task MultiPathSvg_GeneratesArrayConstructor()
    {
        var result = RunWithIconFiles(("icons/lucide/bell.svg", MultiPathSvg));
        var generated = GetGeneratedSource(result, "LucideIcons.g.cs");

        await TUnit.Assertions.Assert.That(generated).IsNotNull();
        await TUnit.Assertions.Assert.That(Has(generated, "new[]")).IsTrue();
        await TUnit.Assertions.Assert.That(Has(generated, "M12 2L2 22h20L12 2z")).IsTrue();
        await TUnit.Assertions.Assert.That(Has(generated, "M12 8v8")).IsTrue();
    }

    // ── Multiple icons in one pack ────────────────────────────────────

    [TUnit.Core.Test]
    public async Task MultipleIcons_AllGenerated()
    {
        var result = RunWithIconFiles(
            ("icons/lucide/arrow-left.svg", SimpleSvg),
            ("icons/lucide/arrow-right.svg", SimpleSvg));
        var generated = GetGeneratedSource(result, "LucideIcons.g.cs");

        await TUnit.Assertions.Assert.That(generated).IsNotNull();
        await TUnit.Assertions.Assert.That(Has(generated, "ArrowLeft")).IsTrue();
        await TUnit.Assertions.Assert.That(Has(generated, "ArrowRight")).IsTrue();
    }

    // ── ViewBox extraction ────────────────────────────────────────────

    [TUnit.Core.Test]
    public async Task CustomViewBox_ExtractedCorrectly()
    {
        var svg = @"<svg viewBox=""0 0 48 48""><path d=""M0 0""/></svg>";
        var result = RunWithIconFiles(("icons/custom/large-icon.svg", svg));
        var generated = GetGeneratedSource(result, "CustomIcons.g.cs");

        await TUnit.Assertions.Assert.That(generated).IsNotNull();
        await TUnit.Assertions.Assert.That(Has(generated, "48f")).IsTrue();
    }

    // ── Auto-generated header ─────────────────────────────────────────

    [TUnit.Core.Test]
    public async Task GeneratedCode_HasAutoGeneratedHeader()
    {
        var result = RunWithIconFiles(("icons/lucide/check.svg", SimpleSvg));
        var generated = GetGeneratedSource(result, "LucideIcons.g.cs");

        await TUnit.Assertions.Assert.That(generated).IsNotNull();
        await TUnit.Assertions.Assert.That(Has(generated, "// <auto-generated/>")).IsTrue();
    }

    // ── SVG extraction unit tests ─────────────────────────────────────

    [TUnit.Core.Test]
    public async Task ExtractSvgPaths_SinglePath()
    {
        var paths = IconPackGenerator.ExtractSvgPaths(SimpleSvg);
        await TUnit.Assertions.Assert.That(paths.Count).IsEqualTo(1);
        await TUnit.Assertions.Assert.That(paths[0]).IsEqualTo("M12 2L2 22h20L12 2z");
    }

    [TUnit.Core.Test]
    public async Task ExtractSvgPaths_MultiplePaths()
    {
        var paths = IconPackGenerator.ExtractSvgPaths(MultiPathSvg);
        await TUnit.Assertions.Assert.That(paths.Count).IsEqualTo(2);
    }

    [TUnit.Core.Test]
    public async Task ExtractViewBox_ReturnsCorrectDimensions()
    {
        var (w, h) = IconPackGenerator.ExtractViewBox(SimpleSvg);
        await TUnit.Assertions.Assert.That(w).IsEqualTo(24f);
        await TUnit.Assertions.Assert.That(h).IsEqualTo(24f);
    }

    [TUnit.Core.Test]
    public async Task ExtractViewBox_NoViewBox_ReturnsDefault()
    {
        var (w, h) = IconPackGenerator.ExtractViewBox("<svg><path d=\"M0 0\"/></svg>");
        await TUnit.Assertions.Assert.That(w).IsEqualTo(24f);
        await TUnit.Assertions.Assert.That(h).IsEqualTo(24f);
    }

    // ── No icons ──────────────────────────────────────────────────────

    [TUnit.Core.Test]
    public async Task NoIconFiles_NoGeneratedSource()
    {
        var result = RunWithNoAdditionalFiles();
        var generated = GetGeneratedSource(result, "Icons.g.cs");

        await TUnit.Assertions.Assert.That(generated is null).IsTrue();
    }

    // ── Test infrastructure ───────────────────────────────────────────

    private static bool Has(string? source, string value)
    {
        return source is not null && source.Contains(value, StringComparison.Ordinal);
    }

    private static GeneratorRunResult RunWithIconFiles(params (string Path, string Content)[] files)
    {
        var additionalTexts = files
            .Select(f => (AdditionalText)new InMemoryAdditionalText(f.Path, f.Content))
            .ToImmutableArray();

        return RunGenerator(additionalTexts);
    }

    private static GeneratorRunResult RunWithNoAdditionalFiles()
    {
        return RunGenerator(ImmutableArray<AdditionalText>.Empty);
    }

    private static GeneratorRunResult RunGenerator(ImmutableArray<AdditionalText> additionalTexts)
    {
        var source = "// Empty compilation";
        var syntaxTree = CSharpSyntaxTree.ParseText(source);

        var references = new List<MetadataReference>();
        foreach (var assembly in AppDomain.CurrentDomain.GetAssemblies())
        {
            if (!assembly.IsDynamic && !string.IsNullOrEmpty(assembly.Location))
            {
                try
                {
                    references.Add(MetadataReference.CreateFromFile(assembly.Location));
                }
                catch
                {
                    // Some assemblies may not be loadable — skip
                }
            }
        }

        var compilation = CSharpCompilation.Create(
            "TestAssembly",
            new[] { syntaxTree },
            references,
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

        var generator = new CascadeGenerator();
        GeneratorDriver driver = CSharpGeneratorDriver.Create(
            generators: new[] { generator.AsSourceGenerator() },
            additionalTexts: additionalTexts);

        driver = driver.RunGeneratorsAndUpdateCompilation(
            compilation, out _, out _);

        return driver.GetRunResult().Results[0];
    }

    private static string? GetGeneratedSource(GeneratorRunResult result, string hintName)
    {
        foreach (var source in result.GeneratedSources)
        {
            if (source.HintName == hintName)
            {
                return source.SourceText.ToString();
            }
        }
        return null;
    }
}
