using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

namespace Cascade.Generators.Tests;

/// <summary>
/// Tests for the localization source generator pipeline (WP-201).
/// Each test provides synthetic AdditionalFiles and verifies that
/// the generator produces the expected <c>S</c> class or diagnostics.
/// </summary>
public class LocalizationGeneratorTests
{
    // ── Basic key generation ──────────────────────────────────────────

    [TUnit.Core.Test]
    public async Task SimpleKeys_GeneratesSClass()
    {
        var json = @"{
  ""NewUser"": {
    ""NameLabel"": ""Full Name"",
    ""WelcomeMessage"": ""Welcome, {0}!""
  }
}";
        var result = RunWithLocaleFile("strings/en.json", json);
        var generated = GetGeneratedSource(result, "S.g.cs");

        await TUnit.Assertions.Assert.That(generated).IsNotNull();
        await TUnit.Assertions.Assert.That(Has(generated, "public static partial class S")).IsTrue();
        await TUnit.Assertions.Assert.That(Has(generated, "public static partial class NewUser")).IsTrue();
        await TUnit.Assertions.Assert.That(Has(generated, "NameLabel")).IsTrue();
        await TUnit.Assertions.Assert.That(Has(generated, "WelcomeMessage")).IsTrue();
    }

    [TUnit.Core.Test]
    public async Task GeneratedKeys_ReturnLocKeyWithQualifiedName()
    {
        var json = @"{
  ""Common"": {
    ""Save"": ""Save""
  }
}";
        var result = RunWithLocaleFile("strings/en.json", json);
        var generated = GetGeneratedSource(result, "S.g.cs");

        await TUnit.Assertions.Assert.That(generated).IsNotNull();
        await TUnit.Assertions.Assert.That(Has(generated, "\"Common.Save\"")).IsTrue();
        await TUnit.Assertions.Assert.That(Has(generated, "new global::Cascade.UI.LocKey")).IsTrue();
    }

    // ── Multiple namespaces ───────────────────────────────────────────

    [TUnit.Core.Test]
    public async Task MultipleNamespaces_GeneratesNestedClasses()
    {
        var json = @"{
  ""Common"": {
    ""Save"": ""Save"",
    ""Cancel"": ""Cancel""
  },
  ""Errors"": {
    ""NotFound"": ""Not found""
  }
}";
        var result = RunWithLocaleFile("strings/en.json", json);
        var generated = GetGeneratedSource(result, "S.g.cs");

        await TUnit.Assertions.Assert.That(generated).IsNotNull();
        await TUnit.Assertions.Assert.That(Has(generated, "class Common")).IsTrue();
        await TUnit.Assertions.Assert.That(Has(generated, "class Errors")).IsTrue();
        await TUnit.Assertions.Assert.That(Has(generated, "Save")).IsTrue();
        await TUnit.Assertions.Assert.That(Has(generated, "Cancel")).IsTrue();
        await TUnit.Assertions.Assert.That(Has(generated, "NotFound")).IsTrue();
    }

    // ── No locale files — normal behavior ──────────────────────────────

    [TUnit.Core.Test]
    public async Task NoLocaleFiles_ProducesNoDiagnosticsOrSource()
    {
        var result = RunWithNoAdditionalFiles();
        var diagnostics = result.Diagnostics;
        var generated = GetGeneratedSource(result, "S.g.cs");

        // When no locale files are present, the generator silently does nothing.
        // Projects that don't use localization should not receive diagnostics.
        await TUnit.Assertions.Assert.That(diagnostics.Length).IsEqualTo(0);
        await TUnit.Assertions.Assert.That(generated is null).IsTrue();
    }

    // ── Auto-generated header ─────────────────────────────────────────

    [TUnit.Core.Test]
    public async Task GeneratedCode_HasAutoGeneratedHeader()
    {
        var json = @"{ ""App"": { ""Title"": ""Hello"" } }";
        var result = RunWithLocaleFile("strings/en.json", json);
        var generated = GetGeneratedSource(result, "S.g.cs");

        await TUnit.Assertions.Assert.That(generated).IsNotNull();
        await TUnit.Assertions.Assert.That(Has(generated, "// <auto-generated/>")).IsTrue();
    }

    // ── JSON parsing unit tests ───────────────────────────────────────

    [TUnit.Core.Test]
    public async Task ParseLocaleJson_DetectsPlaceholders()
    {
        var json = @"{ ""Greet"": { ""Hello"": ""Hello, {0}! You have {1} messages."" } }";
        var result = LocalizationGenerator.ParseLocaleJson(json);

        await TUnit.Assertions.Assert.That(result.ContainsKey("Greet")).IsTrue();
        var entries = result["Greet"];
        await TUnit.Assertions.Assert.That(entries.Count).IsEqualTo(1);
        await TUnit.Assertions.Assert.That(entries[0].PlaceholderCount).IsEqualTo(2);
    }

    [TUnit.Core.Test]
    public async Task ParseLocaleJson_NoPlaceholders_ReturnsZero()
    {
        var json = @"{ ""Common"": { ""OK"": ""OK"" } }";
        var result = LocalizationGenerator.ParseLocaleJson(json);

        var entries = result["Common"];
        await TUnit.Assertions.Assert.That(entries[0].PlaceholderCount).IsEqualTo(0);
    }

    // ── Test infrastructure ───────────────────────────────────────────

    private static bool Has(string? source, string value)
    {
        return source is not null && source.Contains(value, StringComparison.Ordinal);
    }

    private static GeneratorRunResult RunWithLocaleFile(string filePath, string content)
    {
        var additionalTexts = ImmutableArray.Create<AdditionalText>(
            new InMemoryAdditionalText(filePath, content));

        return RunGenerator(additionalTexts);
    }

    private static GeneratorRunResult RunWithNoAdditionalFiles()
    {
        return RunGenerator(ImmutableArray<AdditionalText>.Empty);
    }

    private static GeneratorRunResult RunGenerator(ImmutableArray<AdditionalText> additionalTexts)
    {
        var source = "// Empty compilation";
        var syntaxTree = CSharpSyntaxTree.ParseText(source);

        var references = new List<MetadataReference>();
        foreach (var assembly in AppDomain.CurrentDomain.GetAssemblies())
        {
            if (!assembly.IsDynamic && !string.IsNullOrEmpty(assembly.Location))
            {
                try
                {
                    references.Add(MetadataReference.CreateFromFile(assembly.Location));
                }
                catch
                {
                    // Some assemblies may not be loadable — skip
                }
            }
        }

        var compilation = CSharpCompilation.Create(
            "TestAssembly",
            new[] { syntaxTree },
            references,
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

        var generator = new CascadeGenerator();
        GeneratorDriver driver = CSharpGeneratorDriver.Create(
            generators: new[] { generator.AsSourceGenerator() },
            additionalTexts: additionalTexts);

        driver = driver.RunGeneratorsAndUpdateCompilation(
            compilation, out _, out _);

        return driver.GetRunResult().Results[0];
    }

    private static string? GetGeneratedSource(GeneratorRunResult result, string hintName)
    {
        foreach (var source in result.GeneratedSources)
        {
            if (source.HintName == hintName)
            {
                return source.SourceText.ToString();
            }
        }
        return null;
    }
}

internal sealed class InMemoryAdditionalText : AdditionalText
{
    private readonly string path;
    private readonly string text;

    public InMemoryAdditionalText(string path, string text)
    {
        this.path = path;
        this.text = text;
    }

    public override string Path => path;

    public override SourceText? GetText(CancellationToken cancellationToken = default)
    {
        return SourceText.From(text, Encoding.UTF8);
    }
}
