using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

namespace Cascade.Generators.Tests;

/// <summary>
/// Tests for the navigation route registration source generator pipeline (WP-201).
/// Each test provides synthetic [Route]-decorated classes and verifies that
/// the generator produces the expected route registration table.
/// </summary>
public class NavigationRegistrarTests
{
    private const string StubTypes = @"
using System;

namespace Cascade.UI
{
    public abstract class Node
    {
        public static Node Empty { get; } = null!;
    }

    public abstract class Component : Node, IDisposable
    {
        protected abstract Node Render();
        public void Dispose() { }
    }

    [AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
    public sealed class RouteAttribute : Attribute
    {
        public string Pattern { get; }
        public RouteAttribute(string pattern) { Pattern = pattern; }
    }
}
";

    // ── Basic route registration ──────────────────────────────────────

    [TUnit.Core.Test]
    public async Task SingleRoute_GeneratesRegistration()
    {
        string source = StubTypes + @"
namespace TestApp
{
    [Cascade.UI.Route(""/home"")]
    public class HomePage : Cascade.UI.Component
    {
        protected override Cascade.UI.Node Render() => Cascade.UI.Node.Empty;
    }
}
";
        var result = RunGenerator(source);
        var generated = GetGeneratedSource(result, "RouteRegistration.g.cs");

        await TUnit.Assertions.Assert.That(generated).IsNotNull();
        await TUnit.Assertions.Assert.That(Has(generated, "RouteRegistration")).IsTrue();
        await TUnit.Assertions.Assert.That(Has(generated, "/home")).IsTrue();
        await TUnit.Assertions.Assert.That(Has(generated, "TestApp.HomePage")).IsTrue();
    }

    // ── Multiple routes ───────────────────────────────────────────────

    [TUnit.Core.Test]
    public async Task MultipleRoutes_AllRegistered()
    {
        string source = StubTypes + @"
namespace TestApp
{
    [Cascade.UI.Route(""/home"")]
    public class HomePage : Cascade.UI.Component
    {
        protected override Cascade.UI.Node Render() => Cascade.UI.Node.Empty;
    }

    [Cascade.UI.Route(""/settings"")]
    public class SettingsPage : Cascade.UI.Component
    {
        protected override Cascade.UI.Node Render() => Cascade.UI.Node.Empty;
    }
}
";
        var result = RunGenerator(source);
        var generated = GetGeneratedSource(result, "RouteRegistration.g.cs");

        await TUnit.Assertions.Assert.That(generated).IsNotNull();
        await TUnit.Assertions.Assert.That(Has(generated, "/home")).IsTrue();
        await TUnit.Assertions.Assert.That(Has(generated, "/settings")).IsTrue();
        await TUnit.Assertions.Assert.That(Has(generated, "TestApp.HomePage")).IsTrue();
        await TUnit.Assertions.Assert.That(Has(generated, "TestApp.SettingsPage")).IsTrue();
    }

    // ── Route with parameters ─────────────────────────────────────────

    [TUnit.Core.Test]
    public async Task RouteWithParameters_PatternPreserved()
    {
        string source = StubTypes + @"
namespace TestApp
{
    [Cascade.UI.Route(""/products/{productId}"")]
    public class ProductDetailPage : Cascade.UI.Component
    {
        protected override Cascade.UI.Node Render() => Cascade.UI.Node.Empty;
    }
}
";
        var result = RunGenerator(source);
        var generated = GetGeneratedSource(result, "RouteRegistration.g.cs");

        await TUnit.Assertions.Assert.That(generated).IsNotNull();
        await TUnit.Assertions.Assert.That(Has(generated, "/products/{productId}")).IsTrue();
    }

    // ── No routes ─────────────────────────────────────────────────────

    [TUnit.Core.Test]
    public async Task NoRouteAttributes_NoGeneratedSource()
    {
        string source = StubTypes + @"
namespace TestApp
{
    public class PlainPage : Cascade.UI.Component
    {
        protected override Cascade.UI.Node Render() => Cascade.UI.Node.Empty;
    }
}
";
        var result = RunGenerator(source);
        var generated = GetGeneratedSource(result, "RouteRegistration.g.cs");

        await TUnit.Assertions.Assert.That(generated is null).IsTrue();
    }

    // ── Auto-generated header ─────────────────────────────────────────

    [TUnit.Core.Test]
    public async Task GeneratedCode_HasAutoGeneratedHeader()
    {
        string source = StubTypes + @"
namespace TestApp
{
    [Cascade.UI.Route(""/test"")]
    public class TestPage : Cascade.UI.Component
    {
        protected override Cascade.UI.Node Render() => Cascade.UI.Node.Empty;
    }
}
";
        var result = RunGenerator(source);
        var generated = GetGeneratedSource(result, "RouteRegistration.g.cs");

        await TUnit.Assertions.Assert.That(generated).IsNotNull();
        await TUnit.Assertions.Assert.That(Has(generated, "// <auto-generated/>")).IsTrue();
    }

    // ── Generated route table structure ───────────────────────────────

    [TUnit.Core.Test]
    public async Task GeneratedCode_ReturnsTypeDictionary()
    {
        string source = StubTypes + @"
namespace TestApp
{
    [Cascade.UI.Route(""/home"")]
    public class HomePage : Cascade.UI.Component
    {
        protected override Cascade.UI.Node Render() => Cascade.UI.Node.Empty;
    }
}
";
        var result = RunGenerator(source);
        var generated = GetGeneratedSource(result, "RouteRegistration.g.cs");

        await TUnit.Assertions.Assert.That(generated).IsNotNull();
        await TUnit.Assertions.Assert.That(Has(generated, "Dictionary<string, global::System.Type>")).IsTrue();
        await TUnit.Assertions.Assert.That(Has(generated, "GetRoutes()")).IsTrue();
        await TUnit.Assertions.Assert.That(Has(generated, "typeof(")).IsTrue();
    }

    // ── Test infrastructure ───────────────────────────────────────────

    private static bool Has(string? source, string value)
    {
        return source is not null && source.Contains(value, StringComparison.Ordinal);
    }

    private static GeneratorRunResult RunGenerator(string source)
    {
        var syntaxTree = CSharpSyntaxTree.ParseText(source);

        var references = new List<MetadataReference>();
        foreach (var assembly in AppDomain.CurrentDomain.GetAssemblies())
        {
            if (!assembly.IsDynamic && !string.IsNullOrEmpty(assembly.Location))
            {
                try
                {
                    references.Add(MetadataReference.CreateFromFile(assembly.Location));
                }
                catch
                {
                    // Some assemblies may not be loadable — skip
                }
            }
        }

        var compilation = CSharpCompilation.Create(
            "TestAssembly",
            new[] { syntaxTree },
            references,
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

        var generator = new CascadeGenerator();
        GeneratorDriver driver = CSharpGeneratorDriver.Create(generator);
        driver = driver.RunGeneratorsAndUpdateCompilation(
            compilation, out _, out _);

        return driver.GetRunResult().Results[0];
    }

    private static string? GetGeneratedSource(GeneratorRunResult result, string hintName)
    {
        foreach (var source in result.GeneratedSources)
        {
            if (source.HintName == hintName)
            {
                return source.SourceText.ToString();
            }
        }
        return null;
    }
}
