using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Cascade.Generators;

/// <summary>
/// Incremental source generator that reads font files declared as AdditionalFiles
/// with <c>CascadeFont=true</c> metadata, verifies they are loadable, and generates
/// a typed <c>Fonts</c> class with properties for each declared font.
/// </summary>
/// <remarks>
/// <para>
/// Fonts are declared in the project file as:
/// <code>
/// &lt;AdditionalFiles Include="fonts/Roboto-Regular.ttf" CascadeFont="true" /&gt;
/// </code>
/// The generator produces:
/// <code>
/// public static partial class Fonts
/// {
///     public static string RobotoRegular =&gt; "fonts/Roboto-Regular.ttf";
/// }
/// </code>
/// </para>
/// </remarks>
internal static class FontVerifier
{
    /// <summary>
    /// Registers the font verification pipeline with the incremental generator context.
    /// Called from <see cref="CascadeGenerator.Initialize"/>.
    /// </summary>
    public static void Register(IncrementalGeneratorInitializationContext context)
    {
        // Combine AdditionalTexts with AnalyzerConfigOptions to find
        // files that have CascadeFont metadata set to true.
        var fontFiles = context.AdditionalTextsProvider
            .Combine(context.AnalyzerConfigOptionsProvider)
            .Select((pair, ct) =>
            {
                var (file, optionsProvider) = pair;
                var options = optionsProvider.GetOptions(file);
                options.TryGetValue("build_metadata.AdditionalFiles.CascadeFont", out var isCascadeFont);

                if (!string.Equals(isCascadeFont, "true", System.StringComparison.OrdinalIgnoreCase))
                {
                    return default;
                }

                var text = file.GetText(ct);
                bool fileHasContent = text is not null && text.Length > 0;

                return new FontFileModel(file.Path, fileHasContent);
            })
            .Where(model => model.Path is not null);

        var collected = fontFiles.Collect();

        context.RegisterSourceOutput(collected, static (spc, fonts) =>
        {
            if (fonts.Length == 0)
            {
                return;
            }

            // Report diagnostics for missing font files.
            foreach (var font in fonts)
            {
                if (!font.HasContent)
                {
                    spc.ReportDiagnostic(Diagnostic.Create(
                        FontDiagnostics.FontFileNotFound,
                        Location.None,
                        font.Path));
                }
            }

            var source = GenerateFontsClass(fonts);
            spc.AddSource("Fonts.g.cs", SourceText.From(source, Encoding.UTF8));
        });
    }

    private static string GetFontPropertyName(string filePath)
    {
        var normalized = filePath.Replace('\\', '/');
        var fileName = normalized.Substring(normalized.LastIndexOf('/') + 1);

        // Strip known font extensions
        string[] extensions = { ".ttf", ".otf", ".woff", ".woff2" };
        foreach (var ext in extensions)
        {
            if (fileName.EndsWith(ext, System.StringComparison.OrdinalIgnoreCase))
            {
                fileName = fileName.Substring(0, fileName.Length - ext.Length);
                break;
            }
        }

        return ToPascalCase(fileName);
    }

    private static string ToPascalCase(string name)
    {
        if (string.IsNullOrEmpty(name))
        {
            return "Font";
        }

        var sb = new StringBuilder();
        bool capitalizeNext = true;
        foreach (char c in name)
        {
            if (c == '-' || c == '_' || c == ' ' || c == '.')
            {
                capitalizeNext = true;
                continue;
            }
            if (capitalizeNext)
            {
                sb.Append(char.ToUpperInvariant(c));
                capitalizeNext = false;
            }
            else
            {
                sb.Append(c);
            }
        }
        return sb.Length > 0 ? sb.ToString() : "Font";
    }

    // ── Code generation ───────────────────────────────────────────────

    private static string GenerateFontsClass(
        System.Collections.Immutable.ImmutableArray<FontFileModel> fonts)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by Cascade.Generators — Font Verification Pipeline");
        sb.AppendLine("#pragma warning disable");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Typed font declarations verified at compile time.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static partial class Fonts");
        sb.AppendLine("{");

        for (int i = 0; i < fonts.Length; i++)
        {
            var font = fonts[i];
            var propertyName = GetFontPropertyName(font.Path!);
            var escapedPath = font.Path!.Replace("\\", "\\\\");

            sb.AppendLine($"    public static string {propertyName} => \"{escapedPath}\";");
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    // ── Pipeline data types ───────────────────────────────────────────

    internal readonly struct FontFileModel : System.IEquatable<FontFileModel>
    {
        public string? Path { get; }
        public bool HasContent { get; }

        public FontFileModel(string path, bool hasContent)
        {
            Path = path;
            HasContent = hasContent;
        }

        public bool Equals(FontFileModel other)
        {
            return string.Equals(Path, other.Path, System.StringComparison.Ordinal)
                && HasContent == other.HasContent;
        }

        public override bool Equals(object? obj)
        {
            return obj is FontFileModel other && Equals(other);
        }

        public override int GetHashCode()
        {
            unchecked
            {
                return ((Path?.GetHashCode() ?? 0) * 397) ^ HasContent.GetHashCode();
            }
        }
    }
}
