using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Cascade.Generators;

/// <summary>
/// Incremental source generator that finds all classes decorated with
/// <c>[Route("path")]</c> and generates a static registration method
/// that maps routes to component factories, enabling compile-time
/// route validation and deep link support.
/// </summary>
internal static class NavigationRegistrar
{
    private const string RouteAttributeFullName = "Cascade.UI.RouteAttribute";

    /// <summary>
    /// Registers the navigation route pipeline with the incremental generator context.
    /// Called from <see cref="CascadeGenerator.Initialize"/>.
    /// </summary>
    public static void Register(IncrementalGeneratorInitializationContext context)
    {
        // Stage 1: Syntax filter — look for class declarations with attributes.
        // Stage 2: Semantic enrichment — verify [Route] attribute and extract pattern.
        var routeModels = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: IsRouteCandidate,
                transform: ExtractRouteModel)
            .Where(model => model is not null);

        var collected = routeModels.Collect();

        // Stage 3: Generate the route registration table.
        context.RegisterSourceOutput(collected, static (spc, routes) =>
        {
            if (routes.Length == 0)
            {
                return;
            }

            var validRoutes = new List<RouteModel>();
            foreach (var route in routes)
            {
                if (route is not null)
                {
                    validRoutes.Add(route.Value);
                }
            }

            if (validRoutes.Count == 0)
            {
                return;
            }

            var source = GenerateRouteRegistration(validRoutes);
            spc.AddSource("RouteRegistration.g.cs", SourceText.From(source, Encoding.UTF8));
        });
    }

    // ── Syntax filtering ──────────────────────────────────────────────

    private static bool IsRouteCandidate(SyntaxNode node, System.Threading.CancellationToken ct)
    {
        // Fast filter: only class declarations with at least one attribute
        return node is ClassDeclarationSyntax classDecl
            && classDecl.AttributeLists.Count > 0;
    }

    // ── Semantic analysis ─────────────────────────────────────────────

    private static RouteModel? ExtractRouteModel(
        GeneratorSyntaxContext context,
        System.Threading.CancellationToken ct)
    {
        var classDecl = (ClassDeclarationSyntax)context.Node;
        var semanticModel = context.SemanticModel;
        var classSymbol = semanticModel.GetDeclaredSymbol(classDecl, ct);

        if (classSymbol is null)
        {
            return null;
        }

        // Find the [Route] attribute
        AttributeData? routeAttribute = null;
        foreach (var attr in classSymbol.GetAttributes())
        {
            if (attr.AttributeClass is not null &&
                attr.AttributeClass.ToDisplayString() == RouteAttributeFullName)
            {
                routeAttribute = attr;
                break;
            }
        }

        if (routeAttribute is null)
        {
            return null;
        }

        // Extract the pattern from the constructor argument
        if (routeAttribute.ConstructorArguments.Length == 0 ||
            routeAttribute.ConstructorArguments[0].Value is not string pattern)
        {
            return null;
        }

        var fullTypeName = classSymbol.ToDisplayString();
        var namespaceName = classSymbol.ContainingNamespace?.IsGlobalNamespace == true
            ? null
            : classSymbol.ContainingNamespace?.ToDisplayString();

        return new RouteModel(pattern, fullTypeName, classSymbol.Name, namespaceName);
    }

    // ── Code generation ───────────────────────────────────────────────

    private static string GenerateRouteRegistration(List<RouteModel> routes)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by Cascade.Generators — Navigation Route Pipeline");
        sb.AppendLine("#pragma warning disable");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Auto-generated route registration mapping [Route] patterns to component factories.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static partial class RouteRegistration");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Returns all registered route patterns and their corresponding component type names.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static global::System.Collections.Generic.Dictionary<string, global::System.Type> GetRoutes()");
        sb.AppendLine("    {");
        sb.AppendLine("        return new global::System.Collections.Generic.Dictionary<string, global::System.Type>");
        sb.AppendLine("        {");

        for (int i = 0; i < routes.Count; i++)
        {
            var route = routes[i];
            var separator = i < routes.Count - 1 ? "," : "";
            sb.AppendLine($"            {{ \"{EscapeString(route.Pattern)}\", typeof(global::{route.FullTypeName}) }}{separator}");
        }

        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string EscapeString(string value)
    {
        return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }

    // ── Pipeline data types ───────────────────────────────────────────

    internal readonly struct RouteModel : System.IEquatable<RouteModel>
    {
        public string Pattern { get; }
        public string FullTypeName { get; }
        public string ClassName { get; }
        public string? Namespace { get; }

        public RouteModel(string pattern, string fullTypeName, string className, string? namespaceName)
        {
            Pattern = pattern;
            FullTypeName = fullTypeName;
            ClassName = className;
            Namespace = namespaceName;
        }

        public bool Equals(RouteModel other)
        {
            return string.Equals(Pattern, other.Pattern, System.StringComparison.Ordinal)
                && string.Equals(FullTypeName, other.FullTypeName, System.StringComparison.Ordinal);
        }

        public override bool Equals(object? obj)
        {
            return obj is RouteModel other && Equals(other);
        }

        public override int GetHashCode()
        {
            unchecked
            {
                return ((Pattern?.GetHashCode() ?? 0) * 397) ^ (FullTypeName?.GetHashCode() ?? 0);
            }
        }
    }
}
