<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>InvoiceEditor</AssemblyName>
    <RootNamespace>InvoiceEditor</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IsAotCompatible>true</IsAotCompatible>  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Cascade.UI\Cascade.UI.csproj" />
  </ItemGroup>  <Import Project="..\..\src\Cascade.UI\build\Echostorm.Cascade.UI.targets" />

</Project>
