namespace Cascade.UI;

/// <summary>A key press or release delivered to a <see cref="KeyHandler"/>.</summary>
/// <param name="Key">The key. Modifier keys themselves report <see cref="Key.None"/>.</param>
/// <param name="Modifiers">The modifiers held after this event.</param>
/// <param name="IsRepeat">True for key-downs generated by holding the key (auto-repeat).</param>
public readonly record struct KeyEvent(Key Key, ModifierKeys Modifiers, bool IsRepeat);

/// <summary>
/// Keyboard state. <see cref="ModifiersChanged"/> fires when Ctrl, Shift, Alt or Meta go down or
/// up while the app's window has focus, and with <see cref="ModifierKeys.None"/> when the window
/// loses focus (the key-ups then go to another app).
/// </summary>
public static class Keyboard
{
    private static ModifierKeys last;

    /// <summary>The modifiers physically held right now.</summary>
    public static ModifierKeys Modifiers => OperatingSystem.IsWindows() ? Win32Input.GetAsyncModifierKeys() : last;

    /// <summary>Raised on the UI thread with the new modifier state when it changes.</summary>
    public static event Action<ModifierKeys>? ModifiersChanged;

    internal static void Observe(ModifierKeys modifiers)
    {
        if (modifiers == last)
        {
            return;
        }
        last = modifiers;
        ModifiersChanged?.Invoke(modifiers);
    }
}
