using System;
using System.Collections.Generic;

namespace Cascade.UI;

/// <summary>
/// Theme tokens for chart controls: color palette, axis styles, tooltip, transitions.
/// </summary>
public class ChartTheme
{
    /// <summary>Color palette for chart series.</summary>
    public required ColorPalette Palette { get; init; }

    /// <summary>Text style for axis labels.</summary>
    public required TextStyle AxisLabel { get; init; }

    /// <summary>Text style for the legend.</summary>
    public required TextStyle Legend { get; init; }

    /// <summary>Text style for chart tooltips.</summary>
    public required TextStyle Tooltip { get; init; }

    /// <summary>Grid line color.</summary>
    public required ColorValue GridLine { get; init; }

    /// <summary>Axis line color.</summary>
    public required ColorValue Axis { get; init; }

    /// <summary>Grid line width in logical pixels.</summary>
    public required float GridLineWidth { get; init; }

    /// <summary>Corner radius for bar chart bars.</summary>
    public required float BarRadius { get; init; }

    /// <summary>Transition for data changes.</summary>
    public required Transition DataTransition { get; init; }

    /// <summary>Shadow for chart tooltips.</summary>
    public required ShadowSpec TooltipShadow { get; init; }

    /// <summary>Corner radius for chart tooltips.</summary>
    public required float TooltipRadius { get; init; }

    /// <summary>Creates a default ChartTheme derived from global theme tokens.</summary>
    public static ChartTheme Default(CascadeTheme t)
    {
        ArgumentNullException.ThrowIfNull(t);

        return new ChartTheme
        {
            Palette = ColorPalette.FromTheme(t),
            AxisLabel = t.Typography.Caption,
            Legend = t.Typography.BodySmall,
            Tooltip = t.Typography.Caption,
            GridLine = t.Colors.Border,
            Axis = t.Colors.TextMuted,
            GridLineWidth = 1,
            BarRadius = t.Radius.Sm,
            DataTransition = t.Motion.Default,
            TooltipShadow = t.Shadows.Md,
            TooltipRadius = t.Radius.Sm,
        };
    }
}

/// <summary>
/// A color palette for chart series. Generated automatically from a theme's primary
/// color using OkLCH perceptual spacing, or specified manually.
/// </summary>
public sealed class ColorPalette
{
    private readonly ColorValue[] colors;

    private ColorPalette(ColorValue[] values)
    {
        colors = values;
    }

    /// <summary>Number of colors in the palette.</summary>
    public int Count => colors.Length;

    /// <summary>
    /// A curated, vibrant categorical palette for the first ~10 series — hand-picked so
    /// each is punchy and clearly distinct on both light and dark surfaces. Ordered for
    /// adjacent contrast (consecutive series differ strongly in hue). Earlier the whole
    /// palette was generated by rotating the accent's hue at the accent's own (moderate)
    /// chroma, which left every non-accent hue undersaturated and the charts looking flat.
    /// </summary>
    private static readonly ColorValue[] CuratedSeries =
    [
        new("#007AFF"), // blue
        new("#FF9500"), // orange
        new("#34C759"), // green
        new("#FF2D55"), // pink
        new("#AF52DE"), // purple
        new("#FFCC00"), // yellow
        new("#5AC8FA"), // cyan
        new("#FF3B30"), // red
        new("#5856D6"), // indigo
        new("#00C7BE"), // mint
    ];

    // Overflow (series beyond the curated set) is generated in OkLCH at a fixed, vivid
    // chroma/lightness — deliberately punchier than a single accent's chroma — with hues
    // stepped by the golden angle so any number of extra series stay distinct and never
    // collide with each other. The start hue sits between curated reds so the first
    // overflow colour doesn't echo a curated one.
    private const float OverflowLightness = 0.70f;
    private const float OverflowChroma = 0.165f;
    private const float OverflowHueStart = 200f;
    private const float GoldenAngleDegrees = 137.50776f;

    /// <summary>
    /// The chart series palette: the curated vibrant set (<see cref="CuratedSeries"/>) for
    /// the first colours, then OkLCH-generated overflow for any beyond it. The default
    /// size covers the curated set; charts cycle through it via <see cref="GetColor"/>.
    /// </summary>
    /// <param name="theme">Theme (validated; the palette is intentionally theme-independent
    /// so charts stay vibrant and consistent across themes).</param>
    /// <param name="count">Number of colors to generate.</param>
    public static ColorPalette FromTheme(CascadeTheme theme, int count = 10)
    {
        ArgumentNullException.ThrowIfNull(theme);
        if (count <= 0)
        {
            throw new ArgumentOutOfRangeException(nameof(count), "Palette size must be greater than zero.");
        }

        var values = new ColorValue[count];

        int curated = Math.Min(count, CuratedSeries.Length);
        Array.Copy(CuratedSeries, values, curated);

        for (var i = CuratedSeries.Length; i < count; i++)
        {
            float hue = (OverflowHueStart + GoldenAngleDegrees * (i - CuratedSeries.Length)) % 360f;
            values[i] = ColorValue.OkLch(OverflowLightness, OverflowChroma, hue);
        }

        return new ColorPalette(values);
    }

    /// <summary>
    /// Creates a manual palette from the specified colors.
    /// Validates perceptual distance and warns if colors are too similar.
    /// </summary>
    public static ColorPalette From(params ColorValue[] colors)
    {
        if (colors is null || colors.Length == 0)
        {
            throw new ArgumentException("At least one color must be specified.", nameof(colors));
        }

        var copy = new ColorValue[colors.Length];
        Array.Copy(colors, copy, colors.Length);
        return new ColorPalette(copy);
    }

    /// <summary>Gets the color at the specified index, wrapping if necessary.</summary>
    public ColorValue GetColor(int index)
    {
        if (colors.Length == 0)
        {
            throw new InvalidOperationException("The palette does not contain any colors.");
        }

        if (index < 0)
        {
            throw new ArgumentOutOfRangeException(nameof(index), "Index must be non-negative.");
        }

        return colors[index % colors.Length];
    }
}
